export const primaryColor = '#102540'
export const secondaryColor = '#CEC4B8'
export const backgroundColor = '#F2F2F2'
export const primaryLightColor = '#737979'
export const accentColor = '#50C878'
// export const color5 = '#BFBFBF'
